Repository teo-sprint-17/giboo-click, pull requests merged in 2024-04, with the labels that each got.

#2 공통 인터페이스 작성
  src/types/common.ts
Labels: chore

#6 하단 네비게이션 바 구현 및 화면 너비 확대/축소되지 않는 문제 해결
  public/assets/calendar.svg
  public/assets/grammerly.svg
  public/assets/heart.svg
  public/assets/home-2.svg
  src/app/components/BottomNav/BottomNav.tsx
  src/app/components/BottomNav/NavLink.tsx
  src/app/layout.tsx
  tailwind.config.ts
Labels: feat

#8 하단 네비게이션 바 구현
  public/assets/calendar.svg
  public/assets/grammerly.svg
  public/assets/heart.svg
  public/assets/home-2.svg
  src/app/components/BottomNav/BottomNav.tsx
  src/app/components/BottomNav/NavLink.tsx
  src/app/layout.tsx
  tailwind.config.ts
Labels: feat

#9 이미지 슬라이더 구현
  package-lock.json
  package.json
  public/assets/SUITE-Variable.woff2
  public/assets/card-image1.jpeg
  src/app/globals.css
  src/app/page.tsx
  src/components/Home/Carousel.tsx
  src/components/common/BottomNav/BottomNav.tsx
  src/components/common/BottomNav/NavLink.tsx
Labels: feat

#11 공통 인터페이스 수정 / 더미 데이터 추가
  public/images/donationFoundation/독거노인/독거노인1.jpeg
  public/images/donationFoundation/독거노인/독거노인2.jpeg
  public/images/donationFoundation/장애인/장애인1.jpeg
  public/images/donationFoundation/장애인/장애인2.jpeg
  public/images/donationFoundation/지구촌/지구촌1.jpeg
  public/images/donationFoundation/지구촌/지구촌2.jpeg
  public/images/donationFoundation/지구촌/지구촌3.jpeg
  public/images/donationFoundation/지구촌/지구촌4.jpeg
  public/images/donationFoundation/지구촌/지구촌5.jpeg
  public/images/donationFoundation/지구촌/지구촌6.jpeg
  src/app/globals.css
  src/app/layout.tsx
  src/constants/donationFoundations.ts
  src/types/common.ts
Labels: chore, style

#14 슬라이더 마크업
  src/components/Home/Carousel.tsx
  src/utils/date.ts
Labels: fix, refactor

#17 기부처 카드 컴포넌트 모듈화
  src/app/layout.tsx
  src/app/page.tsx
  src/components/Home/Carousel.tsx
  src/components/common/DonationFoundation/DonationFoundation.tsx
Labels: refactor, style

#18 폰트 적용
  src/app/globals.css
  src/app/layout.tsx
  src/components/common/DonationFoundation/DonationFoundation.tsx
Labels: style

#19 기부하기 컨펌 모달 UI 구현
  public/assets/double-hearts.svg
  src/app/layout.tsx
  src/app/page.tsx
  src/components/Home/DonationButton.tsx
Labels: feat

#23 기부 결과 페이지 구현
  public/assets/images/donationComplete/money-dynamic-color.png
  src/app/donation-complete/page.tsx
  src/components/DonationComplete/AnonymousCheck.tsx
  src/components/DonationComplete/CheeringField.tsx
  src/components/common/LayerLayout.tsx
Labels: feat

#26 메인페이지 UI 수정
  src/app/page.tsx
  src/components/Home/DonationButton.tsx
  src/components/common/Category/Category.tsx
Labels: style

#29 공통 헤더 구현
  public/assets/icons/vuesax/linear/arrow-left.svg
  public/assets/icons/vuesax/linear/element-3.svg
  public/assets/icons/vuesax/linear/send-2.svg
  src/components/common/Header/BackButton.tsx
  src/components/common/Header/Header.tsx
  src/components/common/Header/Title.tsx
Labels: feat

#31 공통 헤더 margin-top 제거 및 className props 추가
  src/components/common/Header/Header.tsx
  src/components/common/Header/Title.tsx
Labels: fix

#33 기부 인증서 Progress bar 컴포넌트 구현
  public/assets/dandelion.png
  src/components/common/Certification/CertificationProgress.tsx
Labels: feat

#34 기부 카운트 UI 추가 및 오타 수정
  src/components/common/Certification/CertificationProgress.tsx
Labels: feat

#35 달력페이지 구현
  public/assets/icons/vuesax/bold/heart.svg
  public/assets/icons/vuesax/bold/medal-star.svg
  public/assets/icons/vuesax/linear/chevron-left.svg
  public/assets/icons/vuesax/linear/chevron-right.svg
  src/app/calendar/page.tsx
  src/components/Calendar/CalendarGrid.tsx
  src/components/Calendar/CalendarHeader.tsx
  src/hooks/useCalendar.ts
  src/utils/date.ts
Labels: feat

#36 인증서 페이지 구현
  public/assets/bear_tree.png
  public/assets/tea.png
  src/app/certification/page.tsx
  src/components/Certification/CerificationCard.tsx
  src/components/Certification/DescriptionItem.tsx
Labels: feat

#40 (wip) 피드 페이지 / 상세 페이지
  src/app/donation-foundation/[id]/page.tsx
  src/app/feed/page.tsx
  src/components/DonationFoundationDetail/DonationDescription.tsx
  src/components/Feed/FeedGroupCard.tsx
  src/components/Feed/FeedHeader.tsx
  src/components/common/DonationFoundationCard/DonationFoundationCard.tsx
  src/hooks/useDonation.ts
  src/hooks/useSession.ts
  src/types/common.ts
Labels: feat

#41 메인 페이지 기부 로직 추가
  src/app/donation-foundation/[id]/page.tsx
  src/app/page.tsx
  src/components/Home/Carousel.tsx
  src/components/Home/DonationButton.tsx
  src/components/Home/DonationFoundations.tsx
  src/hooks/useDonation.ts
  src/hooks/useDonationSwiper.ts
  src/types/common.ts
Labels: feat, fix

#42 마이페이지 기부 로직 추가
  src/app/calendar/page.tsx
  src/components/Mypage/DonationStatus/DonationStatus.tsx
  src/components/Mypage/ProfileBox.tsx
  src/components/common/Certification/CertificationProgress.tsx
  src/types/common.ts
Labels: feat, chore

#43 로그인 페이지 url 변경
  src/app/donation-foundation/[id]/page.tsx
  src/components/Home/DonationButton.tsx
  src/components/common/BottomNav/BottomNav.tsx
Labels: fix

#45 로그인/회원가입 페이지 구현
  public/assets/icons/vuesax/bold/close-circle.svg
  public/assets/icons/vuesax/linear/tick-circle-red.svg
  public/assets/icons/vuesax/linear/tick-circle.svg
  public/assets/sakura.png
  src/app/sign-in/page.tsx
  src/app/sign-up/page.tsx
  src/components/common/InputField.tsx
Labels: feat

#44 준비중인 기능 alert 처리
  src/app/page.tsx
  src/app/sign-in/page.tsx
  src/app/sign-up/page.tsx
  src/components/Mypage/MyDonation.tsx
  src/components/Mypage/ProfileBox.tsx
  src/components/Mypage/Settings.tsx
  src/components/Mypage/SupportAndOther.tsx
Labels: chore

#46 스토리지에 로그인 이력 확인 후 로그인
  src/app/sign-in/page.tsx
Labels: fix

#47 fix : 이벤트 위임
  src/app/sign-in/page.tsx
Labels: fix

#48 확인 멘트 수정
  src/components/Home/DonationButton.tsx
Labels: style

#52 suspense 사용 빌드 에러 해결
  src/app/sign-up/page.tsx
  src/components/SignUp/SignUp.tsx
Labels: fix

#54 배포 테스트 시 UI 깨지는 문제 해결
  public/assets/fonts/LICENSE
  public/assets/fonts/SUITE-Bold.woff2
  public/assets/fonts/SUITE-ExtraBold.woff2
  public/assets/fonts/SUITE-Heavy.woff2
  public/assets/fonts/SUITE-Light.woff2
  public/assets/fonts/SUITE-Medium.woff2
  public/assets/fonts/SUITE-Regular.woff2
  public/assets/fonts/SUITE-SemiBold.woff2
  public/assets/fonts/SUITE.css
  src/app/certification/page.tsx
  src/app/donation-foundation/[id]/page.tsx
  src/app/layout.tsx
  src/components/common/Certification/CertificationProgress.tsx
  src/components/common/InputField.tsx
Labels: fix

#56 input focus 스타일 제거, 전역 title 설정, 더미 인증서 추가
  src/app/certification/page.tsx
  src/app/layout.tsx
  src/components/Certification/CerificationCard.tsx
  src/components/common/BottomNav/BottomNav.tsx
  src/components/common/InputField.tsx
Labels: fix, chore, style

#57 README
  README.md
Labels: docs

#59 메인 페이지 레이아웃 변경 animation으로 임시 해결
  src/app/page.tsx
  src/components/Home/IntroModal.tsx
  tailwind.config.ts
Labels: fix, style
